import React, { useState, useMemo } from 'react';
import { MATERIALS_DB, QUALITY_MULTIPLIERS, CURRENCY_SYMBOL } from './constants';
import { EstimateItem, QualityGrade } from './types';
import { InputSection } from './components/InputSection';
import { EstimateCard } from './components/EstimateCard';
import { SummaryChart } from './components/SummaryChart';
import { AIAdvisor } from './components/AIAdvisor';
import { Calculator, DollarSign, PieChart as PieIcon, List, Info, Download, FileText } from 'lucide-react';
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const App: React.FC = () => {
  const [area, setArea] = useState<number>(0);
  const [quality, setQuality] = useState<QualityGrade>(QualityGrade.Standard);
  const [unselectedIds, setUnselectedIds] = useState<Set<string>>(new Set());
  const [customRates, setCustomRates] = useState<Record<string, number>>({});
  const [activeTab, setActiveTab] = useState<'list' | 'chart'>('list');

  // Calculate items based on inputs
  const items: EstimateItem[] = useMemo(() => {
    const multiplier = QUALITY_MULTIPLIERS[quality];
    
    return MATERIALS_DB.map(material => {
      // Basic logic: base qty * area
      const calculatedQuantity = area * material.baseQuantityPerSqFt;
      
      // Rate logic: Custom rate (if edited) > Base Rate * Quality Multiplier
      const defaultRate = material.baseRate * multiplier;
      const effectiveRate = customRates[material.id] !== undefined 
        ? customRates[material.id] 
        : defaultRate;

      const calculatedCost = calculatedQuantity * effectiveRate;
      
      return {
        ...material,
        calculatedQuantity,
        effectiveRate,
        calculatedCost,
        selected: !unselectedIds.has(material.id)
      };
    });
  }, [area, quality, unselectedIds, customRates]);

  const totalCost = useMemo(() => {
    return items
      .filter(i => i.selected)
      .reduce((acc, curr) => acc + curr.calculatedCost, 0);
  }, [items]);

  const toggleItem = (id: string) => {
    setUnselectedIds(prev => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const handleRateChange = (id: string, newRate: number) => {
    setCustomRates(prev => ({
      ...prev,
      [id]: newRate
    }));
  };

  const handleReset = () => {
    setArea(0);
    setUnselectedIds(new Set());
    setCustomRates({});
    setQuality(QualityGrade.Standard);
  };

  const handleDownloadPDF = () => {
    if (area <= 0) return;

    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    // -- Header --
    doc.setFillColor(30, 41, 59); // Slate 800
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text("Construction Cost Estimate", 14, 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by BuildCost AI on ${date}`, 14, 30);

    // -- Project Summary --
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("Project Summary", 14, 55);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Built-up Area: ${area.toLocaleString('en-IN')} Sq.Ft`, 14, 65);
    doc.text(`Quality Grade: ${quality}`, 14, 72);
    
    // Note: Using "Rs." instead of symbol to avoid font rendering issues
    const formattedTotal = totalCost.toLocaleString('en-IN', { maximumFractionDigits: 2 });
    doc.text(`Total Estimate: Rs. ${formattedTotal}`, 14, 79);
    
    const formattedAvg = (totalCost/area).toLocaleString('en-IN', { maximumFractionDigits: 0 });
    doc.text(`Average Rate: Rs. ${formattedAvg} / Sq.Ft`, 100, 79);

    // -- Table Data --
    const tableRows = items
      .filter(i => i.selected)
      .map(item => [
        item.name,
        item.category,
        `${item.calculatedQuantity.toLocaleString('en-IN', { maximumFractionDigits: 2 })} ${item.unit}`,
        `${item.effectiveRate.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`,
        `${item.calculatedCost.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`
      ]);

    // Total Row
    tableRows.push(['', '', '', 'TOTAL', `${formattedTotal}`]);

    autoTable(doc, {
      startY: 90,
      head: [['Material', 'Category', 'Quantity', 'Rate (Rs.)', 'Cost (Rs.)']],
      body: tableRows,
      theme: 'grid',
      headStyles: { 
        fillColor: [59, 130, 246], // Blue 500
        halign: 'left'
      },
      footStyles: { 
        fillColor: [241, 245, 249], 
        textColor: [30, 41, 59], 
        fontStyle: 'bold',
        halign: 'right' 
      },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 50 }, // Material Name
        1: { cellWidth: 30 }, // Category
        2: { halign: 'right', cellWidth: 35 }, // Quantity
        3: { halign: 'right', cellWidth: 30 }, // Rate
        4: { halign: 'right', cellWidth: 40 }  // Cost
      },
      didParseCell: (data) => {
        // Style total row text
        if (data.row.index === tableRows.length - 1) {
          data.cell.styles.fontStyle = 'bold';
          data.cell.styles.fillColor = [240, 249, 255];
          // Align the label 'TOTAL' to right
          if (data.column.index === 3) {
             data.cell.styles.halign = 'right';
          }
        }
      }
    });

    // -- Footer --
    const finalY = (doc as any).lastAutoTable.finalY || 150;
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text("Disclaimer: This is an approximate estimation based on market averages. Actual costs may vary.", 14, finalY + 15);
    doc.text("Generated via BuildCost AI", 14, finalY + 20);

    doc.save(`Estimation_${area}sqft_${quality}.pdf`);
  };

  return (
    <div className="min-h-screen pb-32 md:pb-12 bg-slate-50">
      {/* Navbar */}
      <nav className="bg-white border-b border-slate-200 sticky top-0 z-30 shadow-sm backdrop-blur-md bg-white/90">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-blue-600 p-2 rounded-lg text-white shadow-blue-200 shadow-lg">
              <Calculator className="w-5 h-5" />
            </div>
            <span className="text-xl font-bold text-slate-800 tracking-tight">
              BuildCost<span className="text-blue-600">AI</span>
            </span>
          </div>
          <div className="flex items-center gap-4">
             {area > 0 && (
                 <button 
                  onClick={handleDownloadPDF}
                  className="hidden sm:flex items-center gap-2 text-sm font-semibold text-blue-600 hover:bg-blue-50 px-3 py-1.5 rounded-lg transition-colors border border-blue-100"
                 >
                   <Download className="w-4 h-4" /> PDF Report
                 </button>
             )}
            <button 
                onClick={handleReset}
                className="text-sm font-medium text-slate-500 hover:text-red-500 transition-colors"
            >
                Reset
            </button>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        
        {/* Intro Text */}
        <div className="mb-8 text-center sm:text-left flex flex-col sm:flex-row justify-between items-end">
          <div>
              <h1 className="text-3xl font-bold text-slate-900 sm:text-4xl mb-2">
                Construction Estimator
              </h1>
              <p className="text-slate-600 max-w-2xl">
                Enter your plot area to get a detailed material and cost breakdown.
              </p>
          </div>
          <div className="hidden lg:block text-right mt-4 sm:mt-0">
             <p className="text-xs text-slate-400 font-medium">CURRENT MARKET RATES</p>
             <p className="text-sm font-semibold text-slate-600">Updated: Q4 2024</p>
          </div>
        </div>

        <div className="flex flex-col lg:flex-row gap-8">
          
          {/* Left Column: Inputs & List */}
          <div className="flex-1">
            <InputSection 
              area={area} 
              setArea={setArea} 
              quality={quality} 
              setQuality={setQuality} 
            />

            {/* Mobile Tabs */}
            <div className="flex lg:hidden bg-white rounded-xl p-1 shadow-sm border border-slate-200 mb-6">
              <button 
                onClick={() => setActiveTab('list')}
                className={`flex-1 py-2 rounded-lg text-sm font-medium flex items-center justify-center gap-2 transition-all ${activeTab === 'list' ? 'bg-slate-100 text-slate-900 shadow-sm' : 'text-slate-500'}`}
              >
                <List className="w-4 h-4" /> Materials
              </button>
              <button 
                onClick={() => setActiveTab('chart')}
                className={`flex-1 py-2 rounded-lg text-sm font-medium flex items-center justify-center gap-2 transition-all ${activeTab === 'chart' ? 'bg-slate-100 text-slate-900 shadow-sm' : 'text-slate-500'}`}
              >
                <PieIcon className="w-4 h-4" /> Analysis
              </button>
            </div>

            {/* List View */}
            <div className={`${activeTab === 'list' ? 'block' : 'hidden lg:block'}`}>
               <div className="flex items-center justify-between mb-4">
                 <h2 className="text-lg font-semibold text-slate-800 flex items-center gap-2">
                    Material Breakdown
                 </h2>
                 {area > 0 && (
                    <span className="text-xs font-bold text-blue-700 bg-blue-50 border border-blue-100 px-3 py-1 rounded-full">
                        {items.filter(i => i.selected).length} Items Selected
                    </span>
                 )}
               </div>
               
               {area > 0 ? (
                 <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                   {items.map(item => (
                     <EstimateCard 
                       key={item.id} 
                       item={item} 
                       onToggle={toggleItem}
                       onRateChange={handleRateChange}
                     />
                   ))}
                 </div>
               ) : (
                 <div className="text-center py-16 bg-white rounded-3xl border border-dashed border-slate-300 shadow-sm">
                   <div className="bg-blue-50 p-6 rounded-full w-24 h-24 flex items-center justify-center mx-auto mb-6">
                     <Calculator className="w-10 h-10 text-blue-500" />
                   </div>
                   <h3 className="text-xl font-bold text-slate-900 mb-2">Ready to Estimate?</h3>
                   <p className="text-slate-500 max-w-xs mx-auto text-lg">Enter your plot area above to see the magic.</p>
                 </div>
               )}
            </div>
          </div>

          {/* Right Column: Chart & Summary (Sticky on Desktop) */}
          <div className={`lg:w-96 shrink-0 ${activeTab === 'chart' ? 'block' : 'hidden lg:block'}`}>
            <div className="sticky top-24 space-y-6">
              
              {/* Total Cost Card */}
              <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-3xl p-6 text-white shadow-2xl relative overflow-hidden group">
                {/* Background Pattern */}
                <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, white 1px, transparent 0)', backgroundSize: '20px 20px' }}></div>
                
                <div className="absolute top-0 right-0 p-3 opacity-10 group-hover:opacity-20 transition-opacity transform group-hover:scale-110 duration-500">
                  <DollarSign className="w-32 h-32" />
                </div>

                <div className="relative z-10">
                    <p className="text-slate-400 text-sm font-bold mb-2 uppercase tracking-widest">Total Estimate</p>
                    <div className="text-4xl sm:text-5xl font-extrabold tracking-tight mb-4 text-white drop-shadow-lg">
                    {CURRENCY_SYMBOL}{totalCost.toLocaleString('en-IN', { maximumFractionDigits: 0 })}
                    </div>
                    
                    <div className="space-y-3">
                        <div className="flex justify-between items-center text-sm border-t border-white/10 pt-3">
                            <span className="text-slate-300">Avg. Cost / Sq.Ft</span>
                            <span className="font-mono font-bold text-white">
                                {area > 0 ? `${CURRENCY_SYMBOL}${(totalCost / area).toLocaleString('en-IN', { maximumFractionDigits: 0 })}` : '-'}
                            </span>
                        </div>
                        <div className="flex justify-between items-center text-sm border-t border-white/10 pt-3">
                            <span className="text-slate-300">Selected Items</span>
                            <span className="font-mono font-bold text-white">
                                {items.filter(i => i.selected).length}
                            </span>
                        </div>
                    </div>

                    {area > 0 && (
                        <button 
                            onClick={handleDownloadPDF}
                            className="mt-6 w-full py-3 bg-white text-slate-900 rounded-xl font-bold text-sm hover:bg-blue-50 transition-colors flex items-center justify-center gap-2"
                        >
                            <FileText className="w-4 h-4" /> Download PDF Report
                        </button>
                    )}
                </div>
              </div>

              {/* Chart */}
              {area > 0 && <SummaryChart items={items} />}

              {/* Disclaimer */}
              {area > 0 && (
                  <div className="bg-blue-50 border border-blue-100 p-4 rounded-xl flex gap-3">
                    <Info className="w-5 h-5 text-blue-500 shrink-0 mt-0.5" />
                    <p className="text-xs text-blue-800 leading-relaxed font-medium">
                    Estimates based on {quality} market rates ({CURRENCY_SYMBOL}). Actuals may vary by brand & location.
                    </p>
                </div>
              )}

            </div>
          </div>
        </div>
      </main>

      {/* Floating Action Button for AI (Mobile & Desktop) */}
      <AIAdvisor 
        area={area}
        quality={quality}
        items={items}
        totalCost={totalCost}
      />

      {/* Mobile Sticky Total (if not on chart tab) */}
      {area > 0 && activeTab === 'list' && (
        <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-slate-200 p-4 shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.1)] lg:hidden z-20 flex justify-between items-center safe-area-pb">
          <div>
            <p className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">Total Estimate</p>
            <p className="text-xl font-bold text-slate-900">{CURRENCY_SYMBOL}{totalCost.toLocaleString('en-IN')}</p>
          </div>
          <button 
             onClick={() => setActiveTab('chart')}
             className="px-5 py-2.5 bg-slate-900 text-white rounded-xl text-sm font-bold shadow-lg"
          >
            Details
          </button>
        </div>
      )}
    </div>
  );
};

export default App;